In [444]:
import torch
from torchvision.utils import save_image
import matplotlib.pyplot as plt
from PIL import Image


In [460]:
#from PIL import Image
img = Image.open('Pooling.png').convert('L')
new_image = img.resize((1000, 1000))
new_image.save('Poolingb.png')

In [446]:
array1 = plt.imread('1.png')
array2 = plt.imread('2.png')
array3 = plt.imread('3.png')
array4 = plt.imread('4.png')
array5 = plt.imread('5.png')
array6 = plt.imread('6.png')
array7 = plt.imread('7.png')
array8 = plt.imread('8.png')
array9 = plt.imread('9.png')
array10 = plt.imread('10.png')
array11 = plt.imread('11.png')
array12 = plt.imread('12.png')
array13 = plt.imread('13.png')
array14 = plt.imread('14.png')
array15 = plt.imread('15.png')
array16 = plt.imread('16.png')
array17 = plt.imread('17.png')
array18 = plt.imread('18.png')
array19 = plt.imread('19.png')
array20 = plt.imread('20.png')
array21 = plt.imread('21.png')


R = plt.imread('11b.png')

In [447]:
array1 = array1.reshape(-1)
R      = R.reshape(-1)
array2 = array2.reshape(-1)
array3 = array3.reshape(-1)
array4 = array4.reshape(-1)
array5 = array5.reshape(-1)
array6 = array6.reshape(-1)
array7 = array7.reshape(-1)
array8 = array8.reshape(-1)
array9 = array9.reshape(-1)
array10 = array10.reshape(-1)
array11 = array11.reshape(-1)
array12 = array12.reshape(-1)
array13 = array13.reshape(-1)
array14 = array14.reshape(-1)
array15 = array15.reshape(-1)
array16 = array16.reshape(-1)
array17 = array17.reshape(-1)
array18 = array18.reshape(-1)
array19 = array19.reshape(-1)
array20 = array20.reshape(-1)
array21 = array21.reshape(-1)




In [448]:
array1= torch.from_numpy(array1)
R     = torch.from_numpy(R)
array2= torch.from_numpy(array2)
array3= torch.from_numpy(array3)
array4= torch.from_numpy(array4)
array5= torch.from_numpy(array5)
array6= torch.from_numpy(array6)
array7= torch.from_numpy(array7)
array8= torch.from_numpy(array8)
array9= torch.from_numpy(array9)
array10= torch.from_numpy(array10)
array11= torch.from_numpy(array11)
array12= torch.from_numpy(array12)
array13= torch.from_numpy(array13)
array14= torch.from_numpy(array14)
array15= torch.from_numpy(array15)
array16= torch.from_numpy(array16)
array17= torch.from_numpy(array17)
array18= torch.from_numpy(array18)
array19= torch.from_numpy(array19)
array20= torch.from_numpy(array20)
array21= torch.from_numpy(array21)

save_image(R.reshape(500,500), 'R.png')



In [449]:
Y=torch.stack((array1, array2,array3,array4,array5,array6,array7,array8,array9,array10,array11,array12,array13,array14,array15,array16,array17,array18,array19,array20,array21), dim=0)

In [450]:
Y.shape


torch.Size([21, 250000])

In [451]:
#save_image(Y[0].reshape(500,500), 'BIN_ima.png')


In [452]:
beta = 0.0001  #blur
beta = 0.41  #blur


In [453]:
Y.T.shape

torch.Size([250000, 21])

In [454]:
R=R.unsqueeze(0)
W = torch.tensor([])

In [455]:
d= beta *R @ Y.T
d

tensor([[30687.5840, 31281.8203, 27073.4609, 31018.1230, 29759.4219, 31479.4082,
         28888.6113, 30604.0586, 31788.1582, 24330.2637, 30489.8438, 32136.3438,
         24341.6016, 30992.0059, 25341.0566, 27773.0879, 23857.0312, 25840.5898,
         29445.6016, 31315.5879, 28385.9082]])

In [456]:
d=torch.nn.functional.softmax(d, dim=1)
d.shape
d

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]])

In [ ]:
W = 

In [457]:
Z= d @ Y
Z=torch.squeeze(Z)
Z.shape

torch.Size([250000])

In [458]:
Z

tensor([0.5098, 0.5098, 0.5098,  ..., 0.3412, 0.3412, 0.3412])

In [459]:
save_image(Z.reshape(500,500), 'Z.png')